//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadCenterV2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Image
    {
        public int Image_ID { get; set; }
        public string Title { get; set; }
        [DisplayName("Image")]
        [Required(ErrorMessage = "Please Select Image")]
        public string ImagePath { get; set; }
        public string Description { get; set; }
        public int User_ID { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
